/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const run: () => void;
export const wasm_bindgen__closure__destroy__he63822833a56ed0d: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h283a945bd0c5f6f1: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h04a55ad596fd87ed: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h01865ab956661ba3: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h2ed9de694f455118: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h4b9fc6a8d3b4cbb1: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h1244bd060843a81a: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1244bd060843a81a_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1244bd060843a81a_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1244bd060843a81a_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1244bd060843a81a_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1244bd060843a81a_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1244bd060843a81a_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h1244bd060843a81a_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hcdb1138e50d81c97: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h6a7ef6fa2181c948: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h819f20ba7eb7ee82: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h700eab209e804bd9: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
