/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const run: () => void;
export const wasm_bindgen__closure__destroy__h5998cb116f7f7ec1: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h05826be8c3467da2: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h7456e0c76bb28477: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h041c367afcb158b7: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h673eae78718694f3: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h9604a820231610fd: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h133814649628e02a: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h133814649628e02a_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h133814649628e02a_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h133814649628e02a_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h133814649628e02a_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h133814649628e02a_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h133814649628e02a_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h133814649628e02a_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__ha7d8d35e87805e30: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h5329d32bf018b4f4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hd700c86398ffc044: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__heaacfaf5ca005d57: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
