/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const run: () => void;
export const wasm_bindgen__closure__destroy__h27a3d3dfee12ecf7: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h013e44e65dab3676: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h1a31ff4d0d6bc13f: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h67549b9a8bd7fd30: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hbf918ba78f09cfca: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h74243e7e3c53ba0d: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h31d067a13a0756d8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h31d067a13a0756d8_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h31d067a13a0756d8_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h31d067a13a0756d8_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h31d067a13a0756d8_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h31d067a13a0756d8_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h31d067a13a0756d8_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h31d067a13a0756d8_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hec1245d4f4781df1: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h2f9fe8b9e4abe3d4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h6df06137df703b13: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hc15b50b141146fb8: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
