/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const run: () => void;
export const wasm_bindgen__closure__destroy__hdebfae03ced3c82b: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h0c70a433fc1c51e4: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h1261628e4d850d10: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h3adda152cd3e3cbd: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hb1efbe771151b276: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__hc1ebcf32a402e91d: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h09b2d0ee560c9489: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h09b2d0ee560c9489_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h09b2d0ee560c9489_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h09b2d0ee560c9489_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h09b2d0ee560c9489_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h09b2d0ee560c9489_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h09b2d0ee560c9489_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h09b2d0ee560c9489_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h91d4ac32017cff19: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h35b7a22d1d08c752: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__hff33dccad965cd69: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hd569457f06bab790: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
