/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const run: () => void;
export const wasm_bindgen__closure__destroy__hdebfae03ced3c82b: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h09862725dc995823: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h1261628e4d850d10: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h0643d44f73936ea3: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hb1efbe771151b276: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h7df346c2c97a25b7: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0234cdbab62f77e6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0234cdbab62f77e6_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0234cdbab62f77e6_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0234cdbab62f77e6_5: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0234cdbab62f77e6_6: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0234cdbab62f77e6_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0234cdbab62f77e6_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0234cdbab62f77e6_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h50e25602a3b7663d: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hce0044a903ab1ded: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h025a8a83a509857e: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__hd569457f06bab790: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
